import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/closebrackets",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/comment",
        "@codemirror/fold",
        "@codemirror/gutter",
        "@codemirror/highlight",
        "@codemirror/history",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/matchbrackets",
        "@codemirror/panel",
        "@codemirror/rangeset",
        "@codemirror/rectangular-selection",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/stream-parser",
        "@codemirror/text",
        "@codemirror/tooltip",
        "@codemirror/view",
        ...builtins,
        "node:events",
        "node:util",
        "node:stream",
        "node:buffer",
        "node:string_decoder",
        "node:url",
        "node:https",
        "node:http",
        "node:zlib",
        "node:child_process",
        "node:os",
        "node:path",
        "node:fs",
        "node:crypto",
        "node:process",
        "node:tty",
        "node:net",
        "node:tls",
        "node:dgram",
        "node:dns",
        "node:querystring",
        "node:assert",
        "node:v8",
        "node:vm",
        "node:module",
        "node:perf_hooks",
        "node:worker_threads",
        "node:cluster",
        "node:repl",
        "node:readline",
        "node:domain",
        "node:async_hooks",
        "node:punycode",
        "node:constants",
        "node:timers",
        "node:console",
        "node:inspector"
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
